### ISSUE TITLE
Demo代码测试Get_Market_History函数出错

### ISSUE THREAD

**Issue by Cobb-Chang** [CybexDex/cybex-node-doc#2]
Ubuntu16.04系统，按照教程安装好Cybex模块，然后运行如下代码，测试Get_Market_History函数：

`import cybex
from datetime import datetime

if __name__ == '__main__':
    NODE_URL='wss://shanghai.51nebula.com/'

    instance = cybex.Cybex(NODE_URL)
    # 创建两个资产对象
    base = cybex.asset.Asset('JADE.ETH', cybex_instance = instance)
    quote = cybex.asset.Asset('CYB', cybex_instance = instance)

    # 创建市场对象
    market = cybex.market.Market(base = base, quote = quote, cybex_instance = instance)

    start = datetime.strptime('2018-08-30 06:00:00', '%Y-%m-%d %H:%M:%S')
    end = datetime.strptime('2018-11-04 06:00:00', '%Y-%m-%d %H:%M:%S')

    # 返回一个kline的序列，所有开始时间在start到end之间的K线
    # 如果在某个时间段内没有成交，则对应的K线不存在，也不会返回。
    kline_arr = market.get_market_history(3600, start, end)
    kline = kline_arr[0]

    # 开盘价格
    print(float(kline['openPrice']))
    # 收盘价格
    print(float(kline['closePrice']))
    # 最高价格
    print(float(kline['highPrice']))
    # 最低价格
    print(float(kline['lowPrice']))`

报出如下错误：

`Traceback (most recent call last):
  File "/home/cobb/cybex/GetMarketHistory.py", line 20, in <module>
    kline_arr = market.get_market_history(3600, start, end)
  File "/usr/local/lib/python3.6/dist-packages/cybex/market.py", line 52, in get_market_history
    api = 'history'
  File "/usr/local/lib/python3.6/dist-packages/cybex/market.py", line 46, in <listcomp>
    for d in self.bitshares.rpc.get_market_history(
  File "/usr/local/lib/python3.6/dist-packages/cybex/market.py", line 16, in __init__
    bitshares_instance = instance
  File "/usr/local/lib/python3.6/dist-packages/bitshares/amount.py", line 98, in __init__
    raise ValueError
ValueError`

请问是哪里出错了。。。

**Comment by cubeyo** [comment]
您好，很抱歉PyCybex库行情部分有一些bug，目前已经修复。
对于1.0.8及以下版本的用户，请使用以下命令升级到最新版本
pip install --upgrade PyCybex==1.0.9
