### ISSUE TITLE
Get_Market_History函数，无法获取早期数据（与上一个问题无关，没有用官方python包）

### ISSUE THREAD

**Issue by Cobb-Chang** [CybexDex/cybex-node-doc#3]
测试代码如下：
`from datetime import datetime,timedelta
import time
import requests
import json

def getDataFromCliWallet(base,quote,unite,start,stop):
        data = {"jsonrpc":"2.0",
        "method":"get_market_history", 
        "params":[base, quote, unite, start, stop],
        "id":1}
        jsondata = json.dumps(data)
        respone = requests.post('http://127.0.0.1:8091/', data=jsondata)
        return json.loads(respone.text)

Quote = 'CYB'
Base = 'JADE.ETH'

respone = getDataFromCliWallet(Quote,Base,3600,"2018-03-21T04:00:00","2018-11-04T09:00:00")
print(respone["result"][0]["key"]["open"])
respone = getDataFromCliWallet(Quote,Base,3600,"2018-03-21T04:00:00","2018-09-24T09:00:00")
print(respone["result"][0]["key"]["open"])`

两次获取的起始时间始终是三月份，但是第二次获取的结束时间有所提前。
但是输出结果如下：
2018-09-23T21:00:00
2018-09-23T21:00:00

似乎超过一定时间的历史数据，就无法获取？是否有办法解决？

**Comment by cubeyo** [comment]
尊敬的用户：

您好

节点提供的K线的种类和条数是由节点的启动参数配置决定的，目前赛贝官方启动的节点，默认配置为保存（15，60，300，3600，86400）秒的k线，每种保存1000条。您请求的3600秒k线，1000条约可以保存41天的数据（如果交易量足够的情况下）。

如果您有获取大量历史k线的需求，可以尝试自己启动节点，通过调整配置参数，让节点保存更久的k线实现。

配置方法见
https://github.com/CybexDex/cybex-node-doc/wiki/%E8%8A%82%E7%82%B9%E6%8F%92%E4%BB%B6%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D

**Comment by Cobb-Chang** [comment]
> 尊敬的用户：
> 
> 您好
> 
> 节点提供的K线的种类和条数是由节点的启动参数配置决定的，目前赛贝官方启动的节点，默认配置为保存（15，60，300，3600，86400）秒的k线，每种保存1000条。您请求的3600秒k线，1000条约可以保存41天的数据（如果交易量足够的情况下）。
> 
> 如果您有获取大量历史k线的需求，可以尝试自己启动节点，通过调整配置参数，让节点保存更久的k线实现。
> 
> 配置方法见
> https://github.com/CybexDex/cybex-node-doc/wiki/%E8%8A%82%E7%82%B9%E6%8F%92%E4%BB%B6%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D

谢谢

**Comment by Cobb-Chang** [comment]
> 尊敬的用户：
> 
> 您好
> 
> 节点提供的K线的种类和条数是由节点的启动参数配置决定的，目前赛贝官方启动的节点，默认配置为保存（15，60，300，3600，86400）秒的k线，每种保存1000条。您请求的3600秒k线，1000条约可以保存41天的数据（如果交易量足够的情况下）。
> 
> 如果您有获取大量历史k线的需求，可以尝试自己启动节点，通过调整配置参数，让节点保存更久的k线实现。
> 
> 配置方法见
> https://github.com/CybexDex/cybex-node-doc/wiki/%E8%8A%82%E7%82%B9%E6%8F%92%E4%BB%B6%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D

你好，创建节点的时候，那个config.ini文件下载不下来哦。。报错：
data/config.ini: No such file or directory

**Comment by Cobb-Chang** [comment]
找到原因了，我自己没有mkdir data

**Comment by Cobb-Chang** [comment]
请问，如果我需要获取全部K线历史，是不是将history_per_size那里空着就行？

**Comment by Cobb-Chang** [comment]
启动节点时报错：

`./bin/witness_node -d data --genesis-json genesis.json --max-ops-per-account 500 --resync-blockchain --replay-blockchain
2222814ms th_a       query_plugin.cpp:56           plugin_set_program_o ] query plugin:  plugin_set_program_options()
2222815ms th_a       witness.cpp:104               plugin_initialize    ] witness plugin:  plugin_initialize() begin
2222815ms th_a       witness.cpp:114               plugin_initialize    ] Public Key: CYB6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2222815ms th_a       witness.cpp:153               plugin_initialize    ] witness plugin:  plugin_initialize() end
2222815ms th_a       db_management.cpp:127         wipe                 ] Wiping database
2222815ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
2222819ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
2222820ms th_a       db_management.cpp:127         wipe                 ] Wiping database
2222820ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
2222820ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
2222820ms th_a       object_database.cpp:106       open                 ] Opening object database from /home/cobb/cybex/data/blockchain ...
2222820ms th_a       object_database.cpp:111       open                 ] Done opening object database.
2222820ms th_a       application.cpp:332           operator()           ] Initializing database...
2222828ms th_a       db_debug.cpp:88               debug_dump           ] total_balances[asset_id_type()].value: 0 core_asset_data.current_supply.value: 95000000000000
2222830ms th_a       application.cpp:134           reset_p2p_node       ] Adding seed node 47.100.231.66:5000
2222830ms th_a       application.cpp:207           reset_p2p_node       ] Configured p2p node to listen on 0.0.0.0:5000
2222831ms th_a       application.cpp:284           reset_websocket_serv ] Configured websocket rpc to listen on [=arg(=127.0.0.1:8090)]
2222831ms th_a       application.cpp:491           startup              ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: Invalid argument
Invalid argument: error converting string to IP endpoint
    {"what":"Invalid argument"}
    th_a  ip.cpp:84 from_string

    {}
    th_a  application.cpp:287 reset_websocket_server
2222831ms th_a       application.cpp:1148          startup              ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: Invalid argument
Invalid argument: error converting string to IP endpoint
    {"what":"Invalid argument"}
    th_a  ip.cpp:84 from_string

    {}
    th_a  application.cpp:287 reset_websocket_server
rethrow
    {}
    th_a  application.cpp:491 startup
2222831ms th_a       main.cpp:292                  main                 ] Exiting with error:
13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: Invalid argument
Invalid argument: error converting string to IP endpoint
    {"what":"Invalid argument"}
    th_a  ip.cpp:84 from_string

    {}
    th_a  application.cpp:287 reset_websocket_server
rethrow
    {}
    th_a  application.cpp:491 startup
9 canceled_exception: Canceled

    {}
    p2p  thread_d.hpp:471 start_next_fiber
2222832ms th_a       db_management.cpp:194         close                ] Rewinding from 0 to 0`

**Comment by Cobb-Chang** [comment]
> 请问，如果我需要获取全部K线历史，是不是将history_per_size那里空着就行？

目前我将那个值设置为：history-per-size = 1000000000

应该够用了
