### ISSUE TITLE
创建节点同步过程中报错

### ISSUE THREAD

**Issue by Cobb-Chang** [CybexDex/cybex-node-doc#5]
ubuntu16.04
以下是报错内容：
`637201ms th_a       witness.cpp:186               plugin_startup       ] No witnesses configured! Please add witness IDs and private keys to configuration.

637201ms th_a       witness.cpp:209               plugin_startup       ] INFO: Disable rte_block_delta generation.

637201ms th_a       witness.cpp:212               plugin_startup       ] witness plugin:  plugin_startup() end

637201ms th_a       main.cpp:276                  main                 ] Started BitShares node on a chain with 3250842 blocks.

637204ms th_a       main.cpp:277                  main                 ] Chain ID is 90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23`

下面是配置文件：
`Endpoint for P2P node to listen on
p2p-endpoint = 0.0.0.0:5000

P2P nodes to connect to on startup (may specify multiple times)
seed-node = 47.100.231.66:5000

# JSON array of P2P nodes to connect to on startup
seed-nodes = []

# Pairs of [BLOCK_NUM,BLOCK_ID] that should be enforced as checkpoints.
# checkpoint = 

# Endpoint for websocket RPC to listen on
rpc-endpoint = 23.83.229.135:8090

# Endpoint for TLS websocket RPC to listen on
# rpc-tls-endpoint = 

# The TLS certificate file for this server
# server-pem = 

# Password for this certificate
# server-pem-password = 

# File to read Genesis State from
# genesis-json = 

# Block signing key to use for init witnesses, overrides genesis file
# dbg-init-key = 

# JSON file specifying API permissions
# api-access = 

# Enable block production, even if the chain is stale.
enable-stale-production = false

# Percent of witnesses (0-99) that must be participating in order to produce blocks
required-participation = false

# ID of witness controlled by this node (e.g. "1.6.5", quotes are required, may specify multiple times)
# witness-id = 

# Tuple of [PublicKey, WIF private key] (may specify multiple times)

# Account ID to track history for (may specify multiple times)
# track-account = 

# Keep only those operations in memory that are related to account history tracking
partial-operations = true

# Maximum number of operations per account will be kept in memory
max-ops-per-account = 50

# Track market history by grouping orders into buckets of equal size measured in seconds specified as a JSON array of numbers
bucket-size = [300,3600,86400]

# How far back in time to track history for each bucket size, measured in the number of buckets (default: 1000)
history-per-size = 1000000000

# declare an appender named "stderr" that writes messages to the console
[log.console_appender.stderr]
stream=std_error

# declare an appender named "p2p" that writes messages to p2p.log
[log.file_appender.p2p]
filename=logs/p2p/p2p.log
# filename can be absolute or relative to this config file

# route any messages logged to the default logger to the "stderr" logger we
# declared above, if they are info level are higher
[logger.default]
level=info
appenders=stderr

# route messages sent to the "p2p" logger to the p2p appender declared above
[logger.p2p]
level=info
appenders=p2p`

请问为啥会报错？

**Comment by Cobb-Chang** [comment]
另外同步速度非常慢，不知是否与seed_node有关？能否增加seed_node？

**Comment by cubeyo** [comment]
您好，启动过程中No witnesses configured! Please add witness IDs and private keys to configuration.这段文字并不是报错。如果您希望参与竞选赛贝出块节点，获取出块的CYB分红，可以在链上创建见证人，然后将您的见证人账号配置到config.ini中，经过所有CYB持有者投票后，您就有希望成为赛贝的超级节点。
同步速度慢与seed_node的数量没有关系。赛贝底层是p2p网络，seed_node只是在启动时用于发现第一个节点。程序会自动发现所有网络中可以连接的节点，并进行区块同步。您可以启动节点后查看本机的5000端口的链接情况，可以看到实际连接的节点情况。目前赛贝的区块同步时间约1天左右（视具体网络情况而定），请耐心等待。

**Comment by Cobb-Chang** [comment]
现在发现同步过程中停在某个区块三四个小时了，我该停止呢。。。还是继续等，搞不清楚情况。。。

**Comment by Cobb-Chang** [comment]
同步了四五天了。。。同步不下去，总是停止再chain ID显示那里，然后进程被Kill

‘
1445146ms th_a       witness.cpp:209               plugin_startup       ] INFO: Disable rte_block_delta generation.
1445146ms th_a       witness.cpp:212               plugin_startup       ] witness plugin:  plugin_startup() end
1445148ms th_a       main.cpp:276                  main                 ] Started BitShares node on a chain with 3272967 blocks.
1445148ms th_a       main.cpp:277                  main                 ] Chain ID is 90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23
Killed

’

**Comment by Cobb-Chang** [comment]
之前的VPS是国外的，换了个国内的就好了。
