### ISSUE TITLE
Bad Cast: Invalid cast from array_type to string

### ISSUE THREAD

**Issue by Cobb-Chang** [CybexDex/cybex-node-doc#6]
尝试利用curl获取账号的limit order挂单信息：
curl --data "{\"jsonrpc\":\"2.0\",\"method\":\"get_account_limit_orders\",\"params\":[[\"baozou-2\",\"JADE.ETH\",\"CYB\",100]],\"id\":1}" 127.0.0.1:8091

然后发生如下报错：
`{"id":1,"jsonrpc":"2.0","error":{"code":1,"message":"Bad Cast: Invalid cast from array_type to string","data":{"code":7,"name":"bad_cast_exception","message":"Bad Cast","stack":[{"context":{"level":"error","file":"variant.cpp","line":485,"method":"fc::variant::as_string","hostname":"","thread_name":"th_a","timestamp":"2018-11-14T06:31:18"},"format":"Invalid cast from ${type} to string","data":{"type":"array_type"}},{"context":{"level":"warn","file":"websocket_api.cpp","line":125,"method":"fc::rpc::websocket_api_connection::on_message","hostname":"","thread_name":"th_a","timestamp":"2018-11-14T06:31:18"},"format":"","data":{"call.method":"get_account_limit_orders","call.params":[["baozou-2","JADE.ETH","CYB",100]]}}]}}}`

同样使用get_market_history的时候，不会报错。
curl --data "{\"id\": 1, \"jsonrpc\":\"2.0\",\"method\": \"call\", \"params\":[0, \"get_market_history\", [\"JADE.ETH\", \"CYB\", 3600, \"2018-10-21T04:00:00\", \"2018-10-21T09:00:00\"]]}" http://127.0.0.1:8091
环境：windows10

**Comment by cubeyo** [comment]
您好，链上没有get_account_limit_orders接口，如果需要查询某个账户的所有挂单，请使用get_full_accounts接口：
curl --data '{"jsonrpc": "2.0", "method": "get_full_accounts", "params": [["baozou-2"], 1], "id": 1}' 127.0.0.1:8090
查看其中的"limit_orders"字段并自行过滤。

**Comment by Cobb-Chang** [comment]
> 您好，链上没有get_account_limit_orders接口，如果需要查询某个账户的所有挂单，请使用get_full_accounts接口：

`{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "Assert Exception: itr != _by_name.end(): no method with name 'get_named_account_balance'",
        "data": {
            "code": 10,
            "name": "assert_exception",
            "message": "Assert Exception",
            "stack": [
                {
                    "context": {
                        "level": "error",
                        "file": "api_connection.hpp",
                        "line": 111,
                        "method": "fc::generic_api::call",
                        "hostname": "",
                        "thread_name": "th_a",
                        "timestamp": "2018-11-14T08:36:03"
                    },
                    "format": "itr != _by_name.end(): no method with name '${name}'",
                    "data": {
                        "name": "get_named_account_balance",
                        "api": [
                            [
                                "about",
                                3
                            ],
                            [
                                "add_operation_to_builder_transaction",
                                5
                            ],
                            [
                                "approve_proposal",
                                99
                            ],
                            [
                                "begin_builder_transaction",
                                4
                            ],
                            [
                                "bid_collateral",
                                55
                            ],
                            [
                                "blind_history",
                                121
                            ],
                            [
                                "blind_transfer",
                                120
                            ],
                            [
                                "borrow_asset",
                                35
                            ],
                            [
                                "borrow_asset_ext",
                                36
                            ],
                            [
                                "broadcast_transaction",
                                10
                            ],
                            [
                                "cancel_order",
                                37
                            ],
                            [
                                "claim_asset_fee_pool",
                                51
                            ],
                            [
                                "create_account_with_brain_key",
                                33
                            ],
                            [
                                "create_asset",
                                41
                            ],
                            [
                                "create_blind_account",
                                117
                            ],
                            [
                                "create_committee_member",
                                57
                            ],
                            [
                                "create_witness",
                                62
                            ],
                            [
                                "create_worker",
                                64
                            ],
                            [
                                "dbg_generate_blocks",
                                103
                            ],
                            [
                                "dbg_make_mia",
                                101
                            ],
                            [
                                "dbg_make_uia",
                                100
                            ],
                            [
                                "dbg_push_blocks",
                                102
                            ],
                            [
                                "dbg_stream_json_objects",
                                104
                            ],
                            [
                                "dbg_update_object",
                                105
                            ],
                            [
                                "derive_owner_keys_from_brain_key",
                                30
                            ],
                            [
                                "dump_private_keys",
                                19
                            ],
                            [
                                "flood_network",
                                106
                            ],
                            [
                                "fund_asset_fee_pool",
                                50
                            ],
                            [
                                "get_account",
                                72
                            ],
                            [
                                "get_account_count",
                                75
                            ],
                            [
                                "get_account_history",
                                76
                            ],
                            [
                                "get_account_history_by_operations",
                                78
                            ],
                            [
                                "get_account_id",
                                73
                            ],
                            [
                                "get_account_limit_orders",
                                89
                            ],
                            [
                                "get_asset",
                                48
                            ],
                            [
                                "get_asset_count",
                                24
                            ],
                            [
                                "get_bitasset_data",
                                49
                            ],
                            [
                                "get_blind_accounts",
                                114
                            ],
                            [
                                "get_blind_balances",
                                116
                            ],
                            [
                                "get_block",
                                74
                            ],
                            [
                                "get_call_orders",
                                91
                            ],
                            [
                                "get_collateral_bids",
                                79
                            ],
                            [
                                "get_committee_member",
                                59
                            ],
                            [
                                "get_dynamic_global_properties",
                                84
                            ],
                            [
                                "get_full_account",
                                81
                            ],
                            [
                                "get_global_properties",
                                83
                            ],
                            [
                                "get_key_label",
                                112
                            ],
                            [
                                "get_limit_orders",
                                90
                            ],
                            [
                                "get_market_history",
                                82
                            ],
                            [
                                "get_my_blind_accounts",
                                115
                            ],
                            [
                                "get_object",
                                85
                            ],
                            [
                                "get_order_book",
                                123
                            ],
                            [
                                "get_private_key",
                                86
                            ],
                            [
                                "get_prototype_operation",
                                96
                            ],
                            [
                                "get_public_key",
                                113
                            ],
                            [
                                "get_relative_account_history",
                                77
                            ],
                            [
                                "get_settle_orders",
                                92
                            ],
                            [
                                "get_transaction_id",
                                40
                            ],
                            [
                                "get_vesting_balances",
                                66
                            ],
                            [
                                "get_witness",
                                58
                            ],
                            [
                                "gethelp",
                                1
                            ],
                            [
                                "global_settle_asset",
                                53
                            ],
                            [
                                "help",
                                0
                            ],
                            [
                                "import_account_keys",
                                27
                            ],
                            [
                                "import_accounts",
                                26
                            ],
                            [
                                "import_balance",
                                28
                            ],
                            [
                                "import_key",
                                25
                            ],
                            [
                                "info",
                                2
                            ],
                            [
                                "is_locked",
                                15
                            ],
                            [
                                "is_new",
                                14
                            ],
                            [
                                "is_public_key_registered",
                                80
                            ],
                            [
                                "issue_asset",
                                47
                            ],
                            [
                                "list_account_balances",
                                22
                            ],
                            [
                                "list_accounts",
                                21
                            ],
                            [
                                "list_assets",
                                23
                            ],
                            [
                                "list_committee_members",
                                61
                            ],
                            [
                                "list_my_accounts",
                                20
                            ],
                            [
                                "list_witnesses",
                                60
                            ],
                            [
                                "load_wallet_file",
                                87
                            ],
                            [
                                "lock",
                                16
                            ],
                            [
                                "network_add_nodes",
                                107
                            ],
                            [
                                "network_get_connected_peers",
                                108
                            ],
                            [
                                "normalize_brain_key",
                                88
                            ],
                            [
                                "preview_builder_transaction",
                                8
                            ],
                            [
                                "propose_builder_transaction",
                                11
                            ],
                            [
                                "propose_builder_transaction2",
                                12
                            ],
                            [
                                "propose_fee_change",
                                98
                            ],
                            [
                                "propose_parameter_change",
                                97
                            ],
                            [
                                "publish_asset_feed",
                                46
                            ],
                            [
                                "quit",
                                124
                            ],
                            [
                                "read_memo",
                                110
                            ],
                            [
                                "receive_blind_transfer",
                                122
                            ],
                            [
                                "register_account",
                                31
                            ],
                            [
                                "remove_builder_transaction",
                                13
                            ],
                            [
                                "replace_operation_in_builder_transaction",
                                6
                            ],
                            [
                                "reserve_asset",
                                52
                            ],
                            [
                                "save_wallet_file",
                                93
                            ],
                            [
                                "sell_asset",
                                34
                            ],
                            [
                                "serialize_transaction",
                                94
                            ],
                            [
                                "set_desired_witness_and_committee_member_count",
                                71
                            ],
                            [
                                "set_fees_on_builder_transaction",
                                7
                            ],
                            [
                                "set_key_label",
                                111
                            ],
                            [
                                "set_password",
                                18
                            ],
                            [
                                "set_voting_proxy",
                                70
                            ],
                            [
                                "settle_asset",
                                54
                            ],
                            [
                                "sign_builder_transaction",
                                9
                            ],
                            [
                                "sign_memo",
                                109
                            ],
                            [
                                "sign_transaction",
                                95
                            ],
                            [
                                "suggest_brain_key",
                                29
                            ],
                            [
                                "transfer",
                                38
                            ],
                            [
                                "transfer2",
                                39
                            ],
                            [
                                "transfer_from_blind",
                                119
                            ],
                            [
                                "transfer_to_blind",
                                118
                            ],
                            [
                                "unlock",
                                17
                            ],
                            [
                                "update_asset",
                                42
                            ],
                            [
                                "update_asset_feed_producers",
                                45
                            ],
                            [
                                "update_asset_issuer",
                                43
                            ],
                            [
                                "update_bitasset",
                                44
                            ],
                            [
                                "update_witness",
                                63
                            ],
                            [
                                "update_worker_votes",
                                65
                            ],
                            [
                                "upgrade_account",
                                32
                            ],
                            [
                                "vote_for_committee_member",
                                68
                            ],
                            [
                                "vote_for_witness",
                                69
                            ],
                            [
                                "whitelist_account",
                                56
                            ],
                            [
                                "withdraw_vesting",
                                67
                            ]
                        ]
                    }
                },
                {
                    "context": {
                        "level": "warn",
                        "file": "websocket_api.cpp",
                        "line": 125,
                        "method": "fc::rpc::websocket_api_connection::on_message",
                        "hostname": "",
                        "thread_name": "th_a",
                        "timestamp": "2018-11-14T08:36:03"
                    },
                    "format": "",
                    "data": {
                        "call.method": "get_named_account_balance",
                        "call.params": [
                            "cobb-chang"
                        ]
                    }
                }
            ]
        }
    }
}`


感谢！刚刚我试过了，get_full_accounts是可以的。多问一句，我在查market API的时候，服务器反馈是由get_account_limit_orders的啊。。。请教一下这是为啥。
